working suggestion form using HTML Imports
grails/grails-guides pull request #9
Opened 2017-07-24 18:00 UTC by benrhine

Importing suggestion form using HTML Imports

2017-07-25 09:40 UTC, sdelamo requested changes

2017-07-25 09:40 UTC, sdelamo commented on .gitignore
> +gradlew
gradlew 
gradlew.bat should not ben ignored

2017-07-25 15:20 UTC, benrhine commented
removed gradlew and gradlew.bat from gitignore

2017-07-26 08:03 UTC, sdelamo approved these changes

2017-07-26 08:13 UTC, merged